name: motomuse
description: MotoMuse â€” AI-native motorcycle navigation app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  firebase_storage: ^12.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  geolocator: ^13.0.0
  go_router: ^14.0.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.9.0
  google_sign_in: ^6.2.0
  http: ^1.2.0
  image_picker: ^1.1.0

dev_dependencies:
  fake_cloud_firestore: ^3.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/textures/texture_dark.jpg
    - assets/textures/texture_light.jpg
